version: 2

models:
  - name: raw_accounts
    description: >
      Raw source data for customer accounts loaded from accounts.csv.
      Contains company details, signup information, and status flags.
    columns:
      - name: account_id
        description: Unique customer identifier (primary key)
      
      - name: account_name
        description: Fictional company name
      
      - name: industry
        description: SaaS vertical category (e.g., DevTools, EdTech)
      
      - name: country
        description: ISO-2 country code
      
      - name: signup_date
        description: Account creation date
      
      - name: referral_source
        description: Customer acquisition channel (organic, ads, event, partner, other)
      
      - name: plan_tier
        description: Initial plan tier at signup (Basic, Pro, Enterprise)
      
      - name: seats
        description: Number of licensed user seats
      
      - name: is_trial
        description: Boolean flag indicating if account is currently in trial period
      
      - name: churn_flag
        description: Boolean flag indicating if account has ever churned

  - name: raw_subscriptions
    description: >
      Raw source data for subscriptions loaded from subscriptions.csv.
      Contains subscription lifecycle information, billing details, and plan tier changes.
    columns:
      - name: subscription_id
        description: Unique subscription identifier (primary key)
      
      - name: account_id
        description: Foreign key to accounts table
        tests:
          - relationships:
              to: ref('raw_accounts')
              field: account_id
      
      - name: start_date
        description: Subscription start date
      
      - name: end_date
        description: Subscription end date (null for active subscriptions)
      
      - name: plan_tier
        description: Plan tier at time of billing (Basic, Pro, Enterprise)
      
      - name: seats
        description: Number of licensed seats for this subscription
      
      - name: mrr_amount
        description: Monthly Recurring Revenue amount in USD
      
      - name: arr_amount
        description: Annual Recurring Revenue amount in USD
      
      - name: is_trial
        description: Boolean flag indicating trial status
      
      - name: upgrade_flag
        description: Boolean flag indicating if plan was upgraded mid-cycle
      
      - name: downgrade_flag
        description: Boolean flag indicating if plan was downgraded mid-cycle
      
      - name: churn_flag
        description: Boolean flag indicating if subscription ended
      
      - name: billing_frequency
        description: Billing cycle frequency (monthly, annual)
      
      - name: auto_renew_flag
        description: Boolean flag indicating if subscription auto-renews

  - name: raw_feature_usage
    description: >
      Raw source data for product feature usage events loaded from feature_usage.csv.
      Contains detailed usage metrics per subscription including frequency, duration, and error tracking.
    columns:
      - name: usage_id
        description: Unique usage event identifier (primary key)
      
      - name: subscription_id
        description: Foreign key to subscriptions table
        tests:
          - relationships:
              to: ref('raw_subscriptions')
              field: subscription_id
      
      - name: usage_date
        description: Date of usage event
      
      - name: feature_name
        description: Name of feature used (from pool of 40 SaaS features)
      
      - name: usage_count
        description: Number of times feature was used
      
      - name: usage_duration_secs
        description: Total time spent using feature in seconds
      
      - name: error_count
        description: Number of errors logged during usage
      
      - name: is_beta_feature
        description: Boolean flag indicating if feature is in beta (approximately 10%)

  - name: raw_support_tickets
    description: >
      Raw source data for customer support tickets loaded from support_tickets.csv.
      Contains ticket lifecycle information, priority levels, response times, and satisfaction metrics.
    columns:
      - name: ticket_id
        description: Unique support ticket identifier (primary key)
      
      - name: account_id
        description: Foreign key to accounts table
        tests:
          - relationships:
              to: ref('raw_accounts')
              field: account_id
      
      - name: submitted_at
        description: Timestamp when ticket was opened
      
      - name: closed_at
        description: Timestamp when ticket was resolved (null for open tickets)
      
      - name: resolution_time_hours
        description: Duration from submission to closure in hours
      
      - name: priority
        description: Ticket priority level (low, medium, high, urgent)
      
      - name: first_response_time_minutes
        description: Time in minutes from submission to first response
      
      - name: satisfaction_score
        description: Customer satisfaction rating 1-5 (null = no response)
      
      - name: escalation_flag
        description: Boolean flag indicating if ticket was escalated

  - name: raw_churn_events
    description: >
      Raw source data for customer churn events loaded from churn_events.csv.
      Contains information about when and why customers left, including refund details and preceding subscription changes.
    columns:
      - name: churn_event_id
        description: Unique churn event identifier (primary key)
      
      - name: account_id
        description: Foreign key to accounts table
        tests:
          - relationships:
              to: ref('raw_accounts')
              field: account_id
      
      - name: churn_date
        description: Date when account churned
      
      - name: reason_code
        description: Categorized reason for churn (pricing, support, features, etc.)
      
      - name: refund_amount_usd
        description: Refund amount in USD ($0 default, 25% have credit/refund)
      
      - name: preceding_upgrade_flag
        description: Boolean flag indicating if account upgraded within 90 days before churn
      
      - name: preceding_downgrade_flag
        description: Boolean flag indicating if account downgraded within 90 days before churn
      
      - name: is_reactivation
        description: Boolean flag indicating if account was previously churned (10% reactivations)
      
      - name: feedback_text
        description: Optional customer feedback comment
